export const SUB_REASON_MAP: Record<string, string[]> = {
  Attendance: [
    "No Call No Show (NCNS)",
    "Consecutive Absences (3+ days)",
    "Pattern Absences (Mon/Fri)",
    "Tardiness – Recurring",
    "Early Departure – Recurring",
    "Unscheduled Leave Abuse",
    "Failure to Follow Call-Out Procedure",
    "Attendance – Other",
  ],
  Behavioral: [
    "Insubordination",
    "Disruptive Behavior in Class",
    "Harassment / Hostile Conduct",
    "Violation of Code of Conduct",
    "Falsification of Records",
    "Unauthorized Device Use",
    "Social Media Policy Violation",
    "Behavioral – Other",
  ],
  Performance: [
    "Failed Knowledge Check (<70%)",
    "Failed Nesting Assessment",
    "Consistently Below KPI Threshold",
    "Failure to Apply Coaching",
    "Poor Quality Scores",
    "Excessive Handle Time",
    "Performance – Other",
  ],
  "Voluntary Resignation": [
    "Accepted Other Offer",
    "Personal / Family Reasons",
    "Relocation",
    "Schedule Conflict",
    "Compensation Dissatisfaction",
    "Role Mismatch / Not a Fit",
    "Resignation – No Reason Given",
  ],
  "Job Abandonment": [
    "No Contact After Day 1 NCNS",
    "No Response to Outreach (48h+)",
    "Abandoned Nesting",
    "Job Abandonment – Other",
  ],
  "Medical / LOA": [
    "Medical Leave Approved",
    "FMLA Request Pending",
    "Non-Medical LOA",
    "Extended Illness Without Documentation",
    "Medical – Other",
  ],
  "Policy Violation": [
    "Background Check Failure",
    "Drug / Alcohol Policy",
    "Confidentiality Breach",
    "Security Violation",
    "Policy Violation – Other",
  ],
  "Training Failure": [
    "Failed Product Certification",
    "Failed Compliance Training",
    "Failed Systems Proficiency Check",
    "Unable to Meet Nesting Readiness",
    "Training Failure – Other",
  ],
  "Personal Reasons": [
    "Transportation Issues",
    "Childcare / Dependent Care",
    "Housing Instability",
    "Financial Hardship",
    "Mental Health Concerns",
    "Personal – Other",
  ],
  "Client / Process Issue": [
    "Client Pulled Training",
    "LOB Cancelled / Restructured",
    "Start Date Changed",
    "Headcount Reduction",
    "Client / Process – Other",
  ],
  Misconduct: [
    "Theft / Fraud",
    "Violence or Threat of Violence",
    "Sexual Misconduct",
    "Discrimination",
    "Retaliation",
    "Misconduct – Other",
  ],
  Communication: [
    "Failure to Communicate Absence",
    "Non-Responsive to Manager",
    "Non-Responsive to HR",
    "Communication – Other",
  ],
  Compliance: [
    "Compliance Test Failure",
    "HIPAA / PII Breach",
    "Non-Disclosure Agreement Violation",
    "Compliance – Other",
  ],
  Technology: [
    "Unable to Meet Tech Requirements",
    "Hardware Failure – Unresolved",
    "Connectivity Issues – Chronic",
    "Technology – Other",
  ],
  Scheduling: [
    "Refused Schedule Assignment",
    "Overtime Non-Compliance",
    "Shift Trade Policy Violation",
    "Scheduling – Other",
  ],
  Relocation: [
    "Moved Out of Serviceable Area",
    "International Move",
    "Relocation – Other",
  ],
  Education: [
    "Returned to School Full-Time",
    "School Schedule Conflict",
    "Education – Other",
  ],
  Compensation: [
    "Rate Dispute",
    "Paycheck Error – Unresolved",
    "Benefits Dissatisfaction",
    "Compensation – Other",
  ],
  "Background / Eligibility": [
    "Failed Drug Screen",
    "Failed Background Check",
    "Work Authorization Issue",
    "Eligibility – Other",
  ],
  Accommodation: [
    "ADA Accommodation – Denied",
    "ADA Accommodation – Pending",
    "Religious Accommodation Conflict",
    "Accommodation – Other",
  ],
  Promotion: [
    "Promoted Out of Training",
    "Internal Transfer",
    "Promotion – Other",
  ],
  Retirement: ["Early Retirement", "Retirement – Other"],
  Termination: [
    "Termination for Cause",
    "Termination – Performance",
    "Termination – Attendance",
    "Termination – Conduct",
    "Termination – Other",
  ],
  "Death / Incapacity": [
    "Trainee Deceased",
    "Medical Incapacitation",
    "Death / Incapacity – Other",
  ],
  Legal: [
    "Court-Ordered Absence",
    "Incarceration",
    "Legal – Other",
  ],
  "Management Decision": [
    "Mutual Agreement",
    "Probationary Release",
    "Management Decision – Other",
  ],
  Other: ["Unclassified / Pending Review", "Other – Specify in Notes"],
};

export const ATTRITION_CATEGORIES = Object.keys(SUB_REASON_MAP);
